/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.54
 * Generated at: 2021-11-21 20:26:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Home</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\" integrity=\"sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh\" crossorigin=\"anonymous\">\r\n");
      out.write("	<style type=\"text/css\">\r\n");
      out.write("		.container{\r\n");
      out.write("			margin-top: 8%;\r\n");
      out.write("			width: 400px;\r\n");
      out.write("			border: ridge 1.5px white;\r\n");
      out.write("			padding: 20px;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("	</style>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"bodyContent\">\r\n");
      out.write("<br><br>\r\n");
      out.write("    <center>\r\n");
      out.write("        <div>\r\n");
      out.write("        \r\n");
      out.write("            <span class=\"heading-page\" id=\"homeWord\"> Reading is dreaming with open eyes</span>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </center>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <main class=\"site-wrapper\">\r\n");
      out.write("        <div class=\"pt-table desktop-768\">\r\n");
      out.write("          <div class=\"pt-tablecell page-home relative\" style=\"background-image: url(https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80);\r\n");
      out.write("          background-position: center;\r\n");
      out.write("          background-size: cover;\">\r\n");
      out.write("                          <div class=\"overlay\"></div>\r\n");
      out.write("      \r\n");
      out.write("                          <div>\r\n");
      out.write("                              <div class=\"row\">\r\n");
      out.write("                                  \r\n");
      out.write("                                      \r\n");
      out.write("      \r\n");
      out.write("                                      <div class=\"hexagon-menu clear\">\r\n");
      out.write("                                          \r\n");
      out.write("                                          \r\n");
      out.write("                                          <div class=\"hexagon-item\">\r\n");
      out.write("                                              <div class=\"hex-item\">\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                              </div>\r\n");
      out.write("                                              <div class=\"hex-item\">\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                              </div>\r\n");
      out.write("                                              <a  class=\"hex-content\">\r\n");
      out.write("                                                  <span class=\"hex-content-inner\">\r\n");
      out.write("                                                      <span class=\"icon\">\r\n");
      out.write("                                                          <i class=\"fa fa-universal-access\"></i>\r\n");
      out.write("                                                      </span>\r\n");
      out.write("                                                      <span class=\"title\">Welcome</span>\r\n");
      out.write("                                                  </span>\r\n");
      out.write("                                                  <svg viewBox=\"0 0 173.20508075688772 200\" height=\"200\" width=\"174\" version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M86.60254037844386 0L173.20508075688772 50L173.20508075688772 150L86.60254037844386 200L0 150L0 50Z\" fill=\"#1e2530\"></path></svg>\r\n");
      out.write("                                              </a>\r\n");
      out.write("                                          </div>\r\n");
      out.write("                                          <div class=\"hexagon-item\">\r\n");
      out.write("                                              <div class=\"hex-item\">\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                              </div>\r\n");
      out.write("                                              <div class=\"hex-item\">\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                              </div>\r\n");
      out.write("                                              <a  class=\"hex-content\" href=\"login.jsp\">\r\n");
      out.write("                                                  <span class=\"hex-content-inner\">\r\n");
      out.write("                                                      <span class=\"icon\">\r\n");
      out.write("                                                          <i class=\"fa fa-bullseye\"></i>\r\n");
      out.write("                                                      </span>\r\n");
      out.write("                                                      <span class=\"title\">Sign in</span>\r\n");
      out.write("                                                  </span>\r\n");
      out.write("                                                  <svg viewBox=\"0 0 173.20508075688772 200\" height=\"200\" width=\"174\" version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M86.60254037844386 0L173.20508075688772 50L173.20508075688772 150L86.60254037844386 200L0 150L0 50Z\" fill=\"#1e2530\"></path></svg>\r\n");
      out.write("                                              </a>\r\n");
      out.write("                                          </div>\r\n");
      out.write("                                          \r\n");
      out.write("                                          <div class=\"hexagon-item\">\r\n");
      out.write("                                              <div class=\"hex-item\">\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                              </div>\r\n");
      out.write("                                              <div class=\"hex-item\">\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                              </div>\r\n");
      out.write("                                              <a  class=\"hex-content\" href=\"signup.jsp\">\r\n");
      out.write("                                                  <span class=\"hex-content-inner\">\r\n");
      out.write("                                                      <span class=\"icon\">\r\n");
      out.write("                                                          <i class=\"fa fa-braille\"></i>\r\n");
      out.write("                                                      </span>\r\n");
      out.write("                                                      <span class=\"title\">Sign up</span>\r\n");
      out.write("                                                  </span>\r\n");
      out.write("                                                  <svg viewBox=\"0 0 173.20508075688772 200\" height=\"200\" width=\"174\" version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M86.60254037844386 0L173.20508075688772 50L173.20508075688772 150L86.60254037844386 200L0 150L0 50Z\" fill=\"#1e2530\"></path></svg>\r\n");
      out.write("                                              </a>    \r\n");
      out.write("                                          </div>\r\n");
      out.write("                                          <div class=\"hexagon-item\">\r\n");
      out.write("                                              <div class=\"hex-item\">\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                              </div>\r\n");
      out.write("                                              <div class=\"hex-item\">\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                              </div>\r\n");
      out.write("                                              <a class=\"hex-content\">\r\n");
      out.write("                                                  <span class=\"hex-content-inner\">\r\n");
      out.write("                                                      <span class=\"icon\">\r\n");
      out.write("                                                          <i class=\"fa fa-id-badge\"></i>\r\n");
      out.write("                                                      </span>\r\n");
      out.write("                                                      <div class=\"stats\">\r\n");
      out.write("                                                        <form action=\"display\" method=\"post\">\r\n");
      out.write("                                                        <input type=\"submit\" value=\"View all books\" name=\"submit\" style=\"background-color: transparent; color: white; border-style: none;\">\r\n");
      out.write("                                                        </form>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                  </span>\r\n");
      out.write("                                                  <svg viewBox=\"0 0 173.20508075688772 200\" height=\"200\" width=\"174\" version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M86.60254037844386 0L173.20508075688772 50L173.20508075688772 150L86.60254037844386 200L0 150L0 50Z\" fill=\"#1e2530\"></path></svg>\r\n");
      out.write("                                              </a>\r\n");
      out.write("                                          </div>\r\n");
      out.write("                                          <div class=\"hexagon-item\">\r\n");
      out.write("                                              <div class=\"hex-item\">\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                              </div>\r\n");
      out.write("                                              <div class=\"hex-item\">\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                              </div>\r\n");
      out.write("                                              <a  class=\"hex-content\" href=\"findbook.jsp\">\r\n");
      out.write("                                                  <span class=\"hex-content-inner\">\r\n");
      out.write("                                                      <span class=\"icon\">\r\n");
      out.write("                                                          <i class=\"fa fa-life-ring\"></i>\r\n");
      out.write("                                                      </span>\r\n");
      out.write("                                                      <span class=\"title\">find Book</span>\r\n");
      out.write("                                                  </span>\r\n");
      out.write("                                                  <svg viewBox=\"0 0 173.20508075688772 200\" height=\"200\" width=\"174\" version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M86.60254037844386 0L173.20508075688772 50L173.20508075688772 150L86.60254037844386 200L0 150L0 50Z\" fill=\"#1e2530\"></path></svg>\r\n");
      out.write("                                              </a>\r\n");
      out.write("                                          </div>\r\n");
      out.write("                                          <div class=\"hexagon-item\">\r\n");
      out.write("                                              <div class=\"hex-item\">\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                              </div>\r\n");
      out.write("                                              <div class=\"hex-item\">\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                              </div>\r\n");
      out.write("                                              <a  class=\"hex-content\" href=\"aboutUs.jsp\">\r\n");
      out.write("                                                  <span class=\"hex-content-inner\">\r\n");
      out.write("                                                      <span class=\"icon\">\r\n");
      out.write("                                                          <i class=\"fa fa-clipboard\"></i>\r\n");
      out.write("                                                      </span>\r\n");
      out.write("                                                      <span class=\"title\">About</span>\r\n");
      out.write("                                                  </span>\r\n");
      out.write("                                                  <svg viewBox=\"0 0 173.20508075688772 200\" height=\"200\" width=\"174\" version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M86.60254037844386 0L173.20508075688772 50L173.20508075688772 150L86.60254037844386 200L0 150L0 50Z\" fill=\"#1e2530\"></path></svg>\r\n");
      out.write("                                              </a>\r\n");
      out.write("                                          </div>\r\n");
      out.write("                                          <div class=\"hexagon-item\">\r\n");
      out.write("                                              <div class=\"hex-item\">\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                              </div>\r\n");
      out.write("                                              <div class=\"hex-item\">\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                                  <div></div>\r\n");
      out.write("                                              </div>\r\n");
      out.write("                                              <a  class=\"hex-content\">\r\n");
      out.write("                                                  <span class=\"hex-content-inner\">\r\n");
      out.write("                                                      <span class=\"icon\">\r\n");
      out.write("                                                          <i class=\"fa fa-map-signs\"></i>\r\n");
      out.write("                                                      </span>\r\n");
      out.write("                                                      <span class=\"title\">Contact</span>\r\n");
      out.write("                                                  </span>\r\n");
      out.write("                                                  <svg viewBox=\"0 0 173.20508075688772 200\" height=\"200\" width=\"174\" version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M86.60254037844386 0L173.20508075688772 50L173.20508075688772 150L86.60254037844386 200L0 150L0 50Z\" fill=\"#1e2530\"></path></svg>\r\n");
      out.write("                                              </a>\r\n");
      out.write("                                          </div>\r\n");
      out.write("                                      </div>\r\n");
      out.write("                                  \r\n");
      out.write("                              </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("        </main>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
